### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by xen-42** [xen-42/DredgeVR#1]
Playable milestone (could release on Patreon + make video)
- [x] Create MonoBehaviour for attaching player camera to boat
- [x] Create separate script for altering settings to lower lag
- [x] Create config file for how much to lower LOD
- [ ] Get particle effects on both eyes else just disable them

Finished milestone
- [x] Make UI viewable in VR
- [ ] ???
- [x] Profit
