### ISSUE TITLE
Pale Reach todo list

### ISSUE THREAD

**Issue by xen-42** [xen-42/DredgeVR#53]
- [x] Move the snow on the title screen to envelope the player
- [x] Adjust the "_IceDepth" shader field on the ice shards
- [x] One ice shard has improper button sizings for the POI
- [x] Pontoon in the ice place has a fifth button that should be larger
- [x] Breaking ice shards tries to show a cutscene, should teleport the player to where the cutscene camera is
